### ISSUE TITLE
[Bug] login process is broken

### ISSUE THREAD

**Issue by mtw20** [sonnylazuardi/chatgpt-desktop#8]
It's now required to click multiple times on login, but maybe it's ChatGPT issue.
Anyway, after logging in, it returns to log in screen again.

**Comment by D3vil0p3r** [comment]
> It's now required to click multiple times on login, but maybe it's ChatGPT issue. Anyway, after logging in, it returns to log in screen again.

Which operating system are you using?

**Comment by D3vil0p3r** [comment]
Hello @sonnylazuardi I join this issue because Im continuing to get the same issue of the guy above.

I noted that the desktop tool could be tied (maybe) with the default browser, because in my Linux machine, where this tool is returning me to the login screen when I insert the correct credentials, if I try to login by Firefox-ESR, I get the same wrong behavior. If I use a Chromium-based browser (like Brave), I can login by this browser.

So, is this desktop tool tied in some way to the default browser used in the system?

**Comment by mtw20** [comment]
> Which operating system are you using?

Windows 11 22H2 22621.900
Right now it's working correctly, maybe ChatGPT bottleneck.
